# Generated by Django 5.1.5 on 2025-01-28 17:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('CNPJ', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ inválido', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP inválido', regex='^\\d{5}-\\d{3}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\+?\\d{1,4}?\\d{9,15}$')])),
                ('nome_completo_prestador', models.CharField(max_length=255)),
                ('cpf_prestador', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('data_nascimento_prestador', models.DateField()),
                ('dia', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('empresas', models.ManyToManyField(related_name='drivers', to='doc.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
