# Generated by Django 5.1.5 on 2025-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='uuid',
        ),
        migrations.AddField(
            model_name='company',
            name='razao_social',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
