# Generated by Django 5.1.5 on 2025-01-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_remove_company_uuid_company_razao_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='cpf_prestador',
        ),
    ]
