# Generated by Django 5.1.5 on 2025-01-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_remove_driver_cpf_prestador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('signed', 'Assinado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='doc.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='doc.driver')),
            ],
        ),
    ]
