# Generated by Django 5.1.5 on 2025-01-29 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_alter_company_options_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subpraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('praca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpracas', to='doc.praca')),
            ],
        ),
    ]
