# Generated by Django 5.1.5 on 2025-01-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_subpraca_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpraca',
            name='regiao',
        ),
    ]
