# Generated by Django 5.1.5 on 2025-01-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_remove_subpraca_regiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='subpraca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='doc.subpraca'),
        ),
    ]
