# Generated by Django 5.1.5 on 2025-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_driver_subpraca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
