# Generated by Django 5.1.5 on 2025-02-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_remove_contract_driver_driver_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nome',
        ),
    ]
