# Generated by Django 5.1.5 on 2025-02-04 14:43

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_remove_company_cpf_remove_company_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('CNPJ', models.CharField(db_index=True, max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ inválido', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP inválido', regex='^\\d{5}-\\d{3}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('razao_social', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa',
                'verbose_name_plural': 'historical Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=None, null=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\+?\\d{1,4}?\\d{9,15}$')])),
                ('nome_completo_prestador', models.CharField(max_length=255)),
                ('data_nascimento_prestador', models.DateField()),
                ('dia', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subpraca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='doc.subpraca')),
            ],
            options={
                'verbose_name': 'historical driver',
                'verbose_name_plural': 'historical drivers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
