# Generated by Django 5.1.5 on 2025-02-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_historicalcompany_historicaldriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
