# Generated by Django 5.1.5 on 2025-02-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_rename_cnpj_company_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='nome_completo_prestador',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='nome_completo_prestador',
        ),
    ]
