# Generated by Django 5.1.5 on 2025-02-04 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0014_remove_driver_nome_completo_prestador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='active',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='active',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XXX.XXXX.XXXX-XX', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XX.XXX.XXX/0001-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XXX.XXXX.XXXX-XX', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XX.XXX.XXX/0001-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
    ]
