# Generated by Django 5.1.5 on 2025-02-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_remove_company_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='a',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
