# Generated by Django 5.1.5 on 2025-02-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0017_contract_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='a',
        ),
    ]
