# Generated by Django 5.1.5 on 2025-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0018_remove_contract_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
