# Generated by Django 5.1.5 on 2025-03-14 15:03

import datetime
import django.db.models.deletion
import fato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=36)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('empresa_id', models.CharField(max_length=36)),
                ('empresa_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.CharField(max_length=9)),
                ('modal_id', models.CharField(blank=True, max_length=36, null=True)),
                ('modal_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('origem', models.CharField(choices=[('indicacao_entregador', 'Indicação Entregador'), ('anuncio', 'Anúncios'), ('leads', 'Leads Entrego'), ('acao_campo', 'Ação de Campo'), ('reentrada', 'Reentrada D&G')], max_length=255)),
                ('motivo_contato', models.CharField(choices=[('nuvem_para_franquia', 'Nuvem para Franquia'), ('franquia_para_franquia', 'Franquia para Franquia'), ('novo_cadastro', 'Novo Cadastro')], max_length=255)),
                ('dt_franquia', models.DateField(blank=True, null=True)),
                ('obs_txt', models.TextField(blank=True, null=True)),
                ('data_snapshot', models.DateField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('driver_id', 'empresa_id', 'data_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo', models.FileField(upload_to=fato.models.upload_to)),
                ('nome', models.CharField(max_length=255)),
                ('filial', models.CharField(max_length=255)),
                ('linhas_importadas', models.IntegerField(default=0)),
                ('linhas_com_erro', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origem',
                'unique_together': {('nome', 'filial', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_lancamento_financeiro', models.CharField(blank=True, max_length=255, null=True)),
                ('data_do_periodo_de_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('data_do_repasse', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo', models.CharField(max_length=255)),
                ('praca', models.CharField(max_length=255)),
                ('subpraca', models.CharField(max_length=255)),
                ('origem', models.CharField(max_length=255)),
                ('id_da_pessoa_entregadora', models.CharField(max_length=255)),
                ('recebedor', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('atingido', models.CharField(max_length=255)),
                ('percentual_de_tempo_disponivel', models.CharField(max_length=255)),
                ('percentual_de_aceitacao', models.CharField(max_length=255)),
                ('percentual_de_conclusao', models.CharField(max_length=255)),
                ('criterio_tempo_disponivel', models.CharField(max_length=255)),
                ('criterio_rotas_aceitas', models.CharField(max_length=255)),
                ('criterio_rotas_concluidas', models.CharField(max_length=255)),
                ('margem_fee_porcentagem', models.CharField(max_length=255)),
                ('origem_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fato.origem')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiro',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_periodo', models.DateField()),
                ('periodo', models.CharField(max_length=255)),
                ('duracao_do_periodo', models.CharField(max_length=255)),
                ('numero_minimo_de_entregadores_regulares_na_escala', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('id_da_pessoa_entregadora', models.CharField(max_length=255)),
                ('pessoa_entregadora', models.CharField(max_length=255)),
                ('praca', models.CharField(max_length=255)),
                ('sub_praca', models.CharField(max_length=255)),
                ('origem', models.CharField(max_length=255)),
                ('tempo_disponivel_escalado', models.CharField(max_length=255)),
                ('tempo_disponivel_absoluto', models.CharField(max_length=255)),
                ('numero_de_corridas_ofertadas', models.IntegerField()),
                ('numero_de_corridas_aceitas', models.IntegerField()),
                ('numero_de_corridas_rejeitadas', models.IntegerField()),
                ('numero_de_corridas_completadas', models.IntegerField()),
                ('numero_de_corridas_canceladas_pela_pessoa_entregadora', models.IntegerField()),
                ('numero_de_pedidos_aceitos_e_concluidos', models.IntegerField()),
                ('soma_das_taxas_das_corridas_aceitas', models.CharField(max_length=255)),
                ('origem_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fato.origem')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performance',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=255)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao', models.TimeField()),
                ('subpraca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos', to='app.subpraca')),
            ],
        ),
    ]
