# Generated by Django 5.1.5 on 2025-02-10 15:06

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XX.XXX.XXX/0001-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XXX.XXXX.XXXX-XX', regex='^\\d{5}-\\d{3}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('razao_social', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('document_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('signed', 'Assinado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XX.XXX.XXX/0001-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato Obrigatório: XXX.XXXX.XXXX-XX', regex='^\\d{5}-\\d{3}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('razao_social', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa',
                'verbose_name_plural': 'historical Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subpraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('praca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpracas', to='app.praca')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=None, null=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\+?\\d{1,4}?\\d{9,15}$')])),
                ('data_nascimento_prestador', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subpraca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.subpraca')),
            ],
            options={
                'verbose_name': 'historical driver',
                'verbose_name_plural': 'historical drivers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('uuid', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('orgao_emissor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\+?\\d{1,4}?\\d{9,15}$')])),
                ('data_nascimento_prestador', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('empresas', models.ManyToManyField(related_name='drivers', to='app.company')),
                ('subpraca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='app.subpraca')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
