# Generated by Django 5.1.5 on 2025-03-14 21:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='tipo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='nome',
            field=app.models.UpperCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='agencia',
            field=app.models.UpperCharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='company',
            name='atividade',
            field=app.models.UpperCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nacionalidade',
            field=app.models.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nome',
            field=app.models.UpperCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='atividade',
            field=app.models.UpperCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='nacionalidade',
            field=app.models.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaldriver',
            name='nome',
            field=app.models.UpperCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modal',
            name='nome',
            field=app.models.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='praca',
            name='nome',
            field=app.models.UpperCharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='praca',
            name='uf',
            field=app.models.UpperCharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='signer',
            name='nome',
            field=app.models.UpperCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='sign_as',
            field=app.models.UpperCharField(max_length=255, verbose_name='Assinado por'),
        ),
        migrations.AlterField(
            model_name='subpraca',
            name='nome',
            field=app.models.UpperCharField(max_length=255),
        ),
    ]
